FROM node:20-alpine

# Set working directory
WORKDIR /app

# We will mount the code via volume in docker-compose.yml
# but we can copy package.json for initial setup
# COPY package*.json ./
# RUN npm install

EXPOSE 5173

CMD sh -c "npm install && npm run dev -- --host 0.0.0.0"
